import React, { useState } from 'react';
import { Database, Copy, Check, RefreshCw, AlertTriangle } from 'lucide-react';

interface SetupProps {
  error?: any;
}

const Setup: React.FC<SetupProps> = ({ error }) => {
  const [copied, setCopied] = useState(false);

  const sqlScript = `
-- EXTENSÕES
create extension if not exists "uuid-ossp";

-- 1. CRIAÇÃO DAS TABELAS (Se não existirem)
create table if not exists users (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  password text,
  level text
);

create table if not exists settings (
  id bigint generated by default as identity primary key,
  name text,
  cnpj text,
  email text,
  phone text,
  address text,
  theme text,
  "warrantyText" text
);

create table if not exists clients (
  id bigint generated by default as identity primary key,
  name text,
  cpf text,
  phone text,
  email text,
  type text default 'Cliente',
  cep text,
  street text,
  number text,
  neighborhood text,
  city text,
  state text
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text,
  unit text,
  stock numeric,
  price text,
  "minStock" numeric
);

create table if not exists services (
  id bigint generated by default as identity primary key,
  name text,
  description text,
  price text
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  client text,
  responsible text,
  "dateInit" text,
  status text,
  "statusColor" text,
  total text,
  description text,
  service text,
  "services_list" jsonb default '[]'::jsonb,
  "products_list" jsonb default '[]'::jsonb
);

-- Renamed from 'sales' to 'service_sales' to avoid AdBlockers blocking requests to '/sales'
create table if not exists service_sales (
  id bigint generated by default as identity primary key,
  client text,
  date text,
  total text,
  status text,
  details text,
  "products_list" jsonb default '[]'::jsonb
);

create table if not exists files (
  id bigint generated by default as identity primary key,
  name text,
  client text,
  date text,
  description text,
  type text,
  size text,
  url text
);

create table if not exists transactions (
  id bigint generated by default as identity primary key,
  type text,
  description text,
  value text,
  "numericValue" numeric,
  date text,
  status text
);

-- 2. CORREÇÃO DE ESTRUTURA (Colunas novas)
do $$
begin
  alter table clients add column if not exists type text default 'Cliente';
  alter table clients add column if not exists cep text;
  alter table clients add column if not exists street text;
  alter table clients add column if not exists number text;
  alter table clients add column if not exists neighborhood text;
  alter table clients add column if not exists city text;
  alter table clients add column if not exists state text;
  
  -- Novas colunas para Orders
  alter table orders add column if not exists description text;
  alter table orders add column if not exists service text;
  alter table orders add column if not exists "services_list" jsonb default '[]'::jsonb;
  alter table orders add column if not exists "products_list" jsonb default '[]'::jsonb;
  
  -- Novas colunas para Sales
  alter table service_sales add column if not exists "products_list" jsonb default '[]'::jsonb;

  -- Coluna para Termos de Garantia
  alter table settings add column if not exists "warrantyText" text;

  -- Coluna para Arquivos
  alter table files add column if not exists client text;
exception
  when others then null;
end $$;

-- 3. PERMISSÕES E SEGURANÇA (RLS)
-- Users
alter table users enable row level security;
drop policy if exists "Public access users" on users;
create policy "Public access users" on users for all using (true) with check (true);

-- Settings
alter table settings enable row level security;
drop policy if exists "Public access settings" on settings;
create policy "Public access settings" on settings for all using (true) with check (true);

-- Clients
alter table clients enable row level security;
drop policy if exists "Public access clients" on clients;
create policy "Public access clients" on clients for all using (true) with check (true);

-- Products
alter table products enable row level security;
drop policy if exists "Public access products" on products;
create policy "Public access products" on products for all using (true) with check (true);

-- Services
alter table services enable row level security;
drop policy if exists "Public access services" on services;
create policy "Public access services" on services for all using (true) with check (true);

-- Orders
alter table orders enable row level security;
drop policy if exists "Public access orders" on orders;
create policy "Public access orders" on orders for all using (true) with check (true);

-- Sales (Renamed to service_sales)
alter table service_sales enable row level security;
drop policy if exists "Public access service_sales" on service_sales;
create policy "Public access service_sales" on service_sales for all using (true) with check (true);

-- Files
alter table files enable row level security;
drop policy if exists "Public access files" on files;
create policy "Public access files" on files for all using (true) with check (true);

-- Transactions
alter table transactions enable row level security;
drop policy if exists "Public access transactions" on transactions;
create policy "Public access transactions" on transactions for all using (true) with check (true);

-- 4. DADOS INICIAIS
delete from users where email = 'dougdeleon@gmail.com';
insert into users (name, email, password, level)
values ('Doug Deleon', 'dougdeleon@gmail.com', '29092019Ic#', 'admin');

insert into settings (name, cnpj, email, phone, address, theme, "warrantyText")
select 'Map-OS Tecnologia', '00.000.000/0001-00', 'contato@mapos.com.br', '(11) 99999-9999', 'Rua Exemplo, 123', 'Padrão', 'A garantia dos serviços prestados é de 90 dias a contar da data de entrega do aparelho, cobrindo apenas o defeito reclamado e os componentes substituídos. A garantia não cobre danos causados por mau uso, quedas, contato com líquidos ou intervenção de terceiros não autorizados. Para validação da garantia, é obrigatória a apresentação deste termo assinado.'
where not exists (select 1 from settings);

-- 5. MIGRAÇÃO DE DADOS ANTIGOS (Sales -> Service_Sales)
do $$
begin
  if exists (select from information_schema.tables where table_name = 'sales') then
     insert into service_sales (client, date, total, status, details)
     select client, date, total, status, details from sales
     where not exists (select 1 from service_sales where service_sales.client = sales.client and service_sales.date = sales.date);
  end if;
end $$;

-- 6. ATUALIZAR CACHE DO POSTGREST
-- Isso garante que as novas colunas sejam reconhecidas imediatamente pela API
NOTIFY pgrst, 'reload config';
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(sqlScript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleRetry = () => {
    window.location.reload();
  };

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center p-4">
      <div className="bg-white rounded-lg shadow-lg max-w-4xl w-full overflow-hidden">
        <div className="bg-brand-blue px-6 py-4 flex items-center justify-between">
            <div className="flex items-center text-white">
                <Database className="h-6 w-6 mr-3" />
                <h1 className="text-xl font-bold">Correção de Banco de Dados</h1>
            </div>
        </div>
        
        <div className="p-6">
            <div className="bg-blue-50 border-l-4 border-blue-400 p-4 mb-6">
                <div className="flex">
                    <div className="flex-shrink-0">
                        <AlertTriangle className="h-5 w-5 text-blue-400" />
                    </div>
                    <div className="ml-3">
                        <p className="text-sm text-blue-700 font-bold">
                            Script de Atualização e Correção
                        </p>
                         <p className="text-xs text-blue-600 mt-1">
                            Este script adiciona suporte a <b>lista de produtos</b> em Vendas e <b>clientes em arquivos</b>.
                        </p>
                    </div>
                </div>
            </div>

            {error && (
              <div className="bg-red-50 border-l-4 border-red-500 p-4 mb-6">
                 <p className="text-sm text-red-700">
                    <strong>Erro detectado:</strong> {error.message || JSON.stringify(error)}
                 </p>
              </div>
            )}

            <p className="text-gray-600 mb-4 text-sm">
                Para aplicar as atualizações na base de dados (Supabase), siga os passos:
            </p>

            <ol className="list-decimal list-inside text-sm text-gray-700 mb-6 space-y-2 px-4">
                <li>Acesse o <strong>SQL Editor</strong> no painel do Supabase.</li>
                <li>Copie o código SQL abaixo e execute (Run).</li>
                <li>Após o sucesso, recarregue esta página.</li>
            </ol>

            <div className="relative border border-gray-200 rounded-md bg-gray-900 overflow-hidden mb-6">
                <div className="flex justify-between items-center px-4 py-2 bg-gray-800 border-b border-gray-700">
                    <span className="text-xs text-gray-400 font-mono">update_database.sql</span>
                    <button 
                        onClick={handleCopy}
                        className="flex items-center text-xs text-white bg-gray-700 hover:bg-gray-600 px-3 py-1 rounded transition-colors"
                    >
                        {copied ? <Check className="h-3 w-3 mr-1" /> : <Copy className="h-3 w-3 mr-1" />}
                        {copied ? 'Copiado!' : 'Copiar SQL'}
                    </button>
                </div>
                <pre className="p-4 overflow-auto max-h-48 text-xs text-green-400 font-mono">
                    {sqlScript}
                </pre>
            </div>

            <div className="flex justify-center">
                <button 
                    onClick={handleRetry}
                    className="flex items-center bg-brand-blue text-white px-6 py-3 rounded-lg hover:bg-blue-600 transition-colors shadow-md font-medium"
                >
                    <RefreshCw className="h-5 w-5 mr-2" />
                    Recarregar Aplicação
                </button>
            </div>
        </div>
      </div>
    </div>
  );
};

export default Setup;